title:   P. Glink
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  [Editing in progress.]
  <br><br>
  Budding BI/Data Analyst with an eye toward Analytics Engineering.
  <br><br>
  <a href="https://www.linkedin.com/in/glinkp/">View My LinkedIn Profile</a>
  <br><br>
 <!---
  <a href="https://public.tableau.com/profile//">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/elvisliang/About-Me-Elvis-Liang-3f4f047d65c5438a8d70686f9e849254">View My Notion Portfolios</a>
  --->
  
theme: jekyll-theme-minimal
 
